name: Test

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
